-- Users Table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    role VARCHAR(50) NOT NULL,
    unique_id VARCHAR(100) UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
    full_name VARCHAR(255),
    department VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_unique_id ON users (unique_id);
CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);

-- Questions Table
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    category VARCHAR(100),
    difficulty VARCHAR(20),
    tags VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    created_by VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usage_count INT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_questions_keyword ON questions (keyword);
CREATE INDEX IF NOT EXISTS idx_questions_category ON questions (category);
CREATE INDEX IF NOT EXISTS idx_questions_is_active ON questions (is_active);

-- Message History Table
CREATE TABLE IF NOT EXISTS message_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_id VARCHAR(100) NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    response_time_ms INT,
    is_ai_generated BOOLEAN DEFAULT FALSE,
    feedback_rating INT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    sender_id VARCHAR(100),
    FOREIGN KEY (sender_id) REFERENCES users(unique_id)
);

CREATE INDEX IF NOT EXISTS idx_message_unique_id ON message_history (unique_id);
CREATE INDEX IF NOT EXISTS idx_message_timestamp ON message_history (timestamp);
CREATE INDEX IF NOT EXISTS idx_message_sender ON message_history (sender_id);

-- Performance Metrics Table
CREATE TABLE IF NOT EXISTS performance_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_id VARCHAR(100) NOT NULL,
    total_questions_answered INT DEFAULT 0,
    average_response_time_ms INT DEFAULT 0,
    average_rating DECIMAL(3,2),
    accuracy_percentage DECIMAL(5,2),
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (unique_id) REFERENCES users(unique_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_performance_unique_id ON performance_metrics (unique_id);

-- Session Table
CREATE TABLE IF NOT EXISTS sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_id VARCHAR(100) NOT NULL,
    user_id VARCHAR(100) NOT NULL,
    session_token VARCHAR(500),
    login_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    logout_at TIMESTAMP,
    is_active BOOLEAN DEFAULT TRUE,
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    FOREIGN KEY (unique_id) REFERENCES users(unique_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sessions_unique_id ON sessions (unique_id);
CREATE INDEX IF NOT EXISTS idx_sessions_is_active ON sessions (is_active);

-- System Logs Table
CREATE TABLE IF NOT EXISTS system_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor VARCHAR(255),
    target_unique_id VARCHAR(100),
    action TEXT,
    details TEXT,
    status VARCHAR(50),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_logs_timestamp ON system_logs (timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_actor ON system_logs (actor);
CREATE INDEX IF NOT EXISTS idx_logs_status ON system_logs (status);
